### ISSUE TITLE
Digg and Weibo

### ISSUE THREAD

**Issue by PritishC** [triplej0079/DeepIM#2]
Hi, many thanks for the code for your paper.

I wanted to ask about the digg and weibo datasets, since they aren't available in the data directory on the repo. These are of interest because they're the largest graphs amongst all datasets and are supposed to have real-world cascade data in the form of diffusion chains (as per IMINFECTOR paper, since it is part of the baselines). Is it possible to get them on Gdrive if they're too big for github?

I also wanted to ask about the training procedure. It is claimed in the paper that using IC/LT diffusion models as input to the algorithm/learning model is limiting, which makes sense. But the ground-truth training data still consists of (**x**, y) pairs generated using these diffusion models. Does this have any effect on model learning?

Thank you again.

**Comment by masa569** [comment]
Hi, I also want to ask how to use the code for another real dataset, I tried to do that but we don't know how it is formatted, if there is any explanation about that ... 

> Hi, many thanks for the code for your paper.
> 
> I wanted to ask about the digg and weibo datasets, since they aren't available in the data directory on the repo. These are of interest because they're the largest graphs amongst all datasets and are supposed to have real-world cascade data in the form of diffusion chains (as per IMINFECTOR paper, since it is part of the baselines). Is it possible to get them on Gdrive if they're too big for github?
> 
> I also wanted to ask about the training procedure. It is claimed in the paper that using IC/LT diffusion models as input to the algorithm/learning model is limiting, which makes sense. But the ground-truth training data still consists of (**x**, y) pairs generated using these diffusion models. Does this have any effect on model learning?
> 
> Thank you again.

**Comment by triplej0079** [comment]
The edge list for Weibo and Digg datasets can be obtained from https://github.com/geopanag/IMINFECTOR. For generating the (x, y) pairs, please refer to the settings of the diffusion_evaluation function in main/utils.py.
